#SPARQL query templae
#Built work - fields
#Author Matteo Lorenzini ETH Zurich, GTA 


#https://resource.swissartresearch.net/fieldDefinition/Creator
#Insert


#SELECT

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crmarch: <http://www.tobedetermined.org/CRMarch/>
PREFIX frbr: <http://www.cidoc-crm.org/frbr/>

SELECT ?value
WHERE {
  ?production <http://www.cidoc-crm.org/cidoc-crm/P108_produced> $subject .
  ?production <http://www.cidoc-crm.org/cidoc-crm/P14_carried_out_by> ?value_creator .
  ?value_creator rdfs:label ?value.
}

#Delete

#http://resource.swissartresearch.net/fieldDefinition/Title

#Insert
INSERT {  $subject a <http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object>.
          ?subject  rdfs:label ?value}

          WHERE {}

#SELECT

SELECT ?value ?label

WHERE {
    $subject a <http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object>.
    ?subject  rdfs:label ?value
}


#Delete
